# Generated by Django 4.2.3 on 2023-07-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('email', models.EmailField(blank=True, default='', max_length=250)),
                ('mobile', models.CharField(blank=True, default='', max_length=11)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
